version: "2"

linters:
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofumpt

  settings:
    gofumpt:
      extra-rules: true

issues:
  exclude-dirs:
    - examples
