version: "2"

linters:
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - unused

  exclusions:
    paths:
      - examples

formatters:
  enable:
    - gofumpt

  settings:
    gofumpt:
      extra-rules: true
